// src/header.jsx
import React from "react";
import Logo from "./assets/logos/logo.svg";
function Header() {
  return (
    <div className="content">
      <div className="container">
        <div className="logo">
          <img src={Logo} alt="logo" />
        </div>
      </div>
    </div>
  );
}

export default Header;

// yourcode/mislene-zup/src/components/header/index.vue
<template>
  <header>
    <div class="container">
      <v-row>
        <v-col
          md="12"
        >
          <img
            class="logo-zup"
            src="@/assets/imgs/logo.png"
            alt="logo-zup"
          >
        </v-col>
      </v-row>
    </div>
  </header>
</template>

<style lang="scss">
  @import './style.scss';
</style>

<script src="./scripts.js" />
